apiVersion: v2
appVersion: 2.9.3
description: The official Helm chart to deploy Apache Airflow, a platform to programmatically
  author, schedule, and monitor workflows
keywords:
- apache
- airflow
- workflow
- scheduler
name: airflow
type: application
version: 1.15.0